version: "3"

services:
  frontend:
    # New
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: yarn run start
    tty: true
    ports:
      - 3000:3000

    ### Old
    # build: .
    # environment:
    #   - NODE_ENV=development
    # volumes:
    #   - ./:/usr/src/app
    # command: sh -c 'cd frontend && yarn start'
    # ports:
    #   - '3000:3000'
    # tty: true
